[project]
name = "datasette-debug-gotham"
version = "0.1.0a2"
description = "A debugging utility for testing actor permissions/actions with DC Superheros (superman, Batman, Daily Planet, etc.)"
readme = "README.md"
authors = [{name = "Alex Garcia"}]
license = "Apache-2.0"
classifiers=[
    "Framework :: Datasette"
]
requires-python = ">=3.10"
dependencies = [
    "datasette",
    "datasette-debug-bar",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project.urls]
Homepage = "https://github.com/datasette/datasette-debug-gotham"
Changelog = "https://github.com/datasette/datasette-debug-gotham/releases"
Issues = "https://github.com/datasette/datasette-debug-gotham/issues"
CI = "https://github.com/datasette/datasette-debug-gotham/actions"

[project.entry-points.datasette]
debug_gotham = "datasette_debug_gotham"

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"

[tool.setuptools.package-data]
datasette_debug_gotham = ["static/*", "templates/*"]

